-- Change contacts_requests id to an auto-incrementing integer (bigint identity)
alter table public.contacts_requests drop constraint if exists contacts_requests_pkey;

alter table public.contacts_requests drop column if exists id;

alter table public.contacts_requests add column id bigint generated by default as identity primary key;

comment on column public.contacts_requests.id is 'Incremental numerical primary key for the contact request.';
